# Operon TechnologiesTM Configuration
#     RedBlocks 2 by Techzune

# IGNORE THIS - CHANGING IT WILL RESET YOUR CONFIG!
configVersion: '1.6'

# Checks for updates from BukkitDev
updateCheck: 'true'

rules:
  # The maximum amount of controlled blocks per RedBlock
  maxBlocksPer: 100

  # The maximum amount of RedBlocks created per player
  maxRedBlocksPer: 15

redblocks:
  # The block ID of a RedBlock
  #    WARNING: This may [most likely] wipe ALL existing RedBlocks!
  blockID: '42'

  # Drops all controlled blocks when the RedBlock is destroyed
  #    Turning this on can be considered annoying if the player's inventory is full.
  drops: 'false'

  # Plays sound effects when editing RedBlocks
  soundFX: 'true'

  # The ID of the item that is used while sneaking to break a RedBlock
  destroyItem: '280'

  # The time in milliseconds during which the RedBlock will pause after a redstone signal
  #     This prevents clocks that lag the server. The higher the safer, but too high can be annoying!
  redstoneTimeout: '750'

worldedit:
  # The maximum number of blocks added to a RedBlock at a time via WorldEdit
  maxAtOnce: '1000000'

  # Prevents bedrock from being added to a RedBlock via WorldEdit
  preventBedrock: 'true'

gc:
  # Requests the garbage collector when deemed necessary
  onWorldEdit: 'true'
  onDisableRedBlock: 'true'
  onEnableRedBlock: 'true'
  onDestroyRedBlock: 'true'
  
# Thank You For Completing The Configuration!
# If you would like any config options added, feel free to suggest them!
# We appreciate your feedback about Operon Technologies or our plugins!

# ~~ Operon TechnologiesTM ~~ RedBlocks 2 ~~ 2014 ~~ #